- name: ONTAP Setup and Storage Config for Oracle
  collections:
    - netapp.ontap
  hosts: "{{ hosts | default ('ontap') }}"
  connection: local
  gather_facts: false
  vars_files:
    - roles/ontap/defaults/main.yml    
    - ontap_vars.yml
  vars_prompt:
    - name: vsadmin_password
      prompt: Enter vsadmin password for the SVM
      unsafe: yes
      private: yes
  roles:
    - role: ontap
      #  tags:


