---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Check whether the pre-requisites of ONTAP cluster are met
# Pre-requisites:
# Verify cluster node names match what was is in ontap_vars
# Verify aggregate names match what is in ontap_vars
# Verify NFS vlan has been created and matches ontap_vars
# Verify ifgrp has been created
# Set variable facts for the following: nfs lifs, svm specs, svm root volume, svm root mirror volumes, nfs export policy
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Pre-req check
      include_tasks: pre_req.yml
      tags:
        - pre_req
        - ontap_config_svm
        - ontap_ls_mirror_volumes
        - ontap_config_job_schedule
        - ontap_snapmirror_relationship
        - ontap_unlock_svm_admin
        - ontap_svm_mgmt_lif
        - ontap_export_policy_rule
        - ontap_export_policy_apply
        - ontap_flexvol_create
        - ontap_nfs_lif
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Check for ONTAP Pre-requisites] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ONTAP Tasks for Creation of SVM for Oracle DB
# Generate list of data aggregates for SVM
# Create SVM with NFS protocol
# Enable NFS Protocol for SVM
# Create load-sharing mirror volume for Oracle SVM root volume
# Create job schedule for the snapmirror of SVM root volume
# Create snapmirror relationships between SVM root volume and load-sharing mirror volumes
# Initialize snapmirror relationship
# Set password for vsadmin (Account cannot be unlocked with password)
# Unlock vsadmin user for Oracle SVM
# Create LIF for Oracle SVM Management
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: SVM Setup
      include_tasks: svm_create.yml
      tags:
        - ontap_config_svm
        - ontap_ls_mirror_volumes
        - ontap_config_job_schedule
        - ontap_snapmirror_relationship
        - ontap_unlock_svm_admin
        - ontap_svm_mgmt_lif  
  when: ontap_nodes_validity|bool and ontap_aggregates_validity|bool and ontap_vlan_validity|bool
  rescue: 
    - name: Failure message
      debug:
        msg:
          - "TASK [SVM Setup] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ONTAP tasks for NFS export policy
# Create SVM NFS export policy rules
# Add NFS export policy to the root volume
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: NFS Exports
      include_tasks: nfs_export_policy.yml
      tags:
        - ontap_export_policy_rule
        - ontap_export_policy_apply
  when: ontap_nodes_validity|bool and ontap_aggregates_validity|bool and ontap_vlan_validity|bool
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [NFS Exports] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ONTAP task for creating Flexvols for Oracle Database
# Create Flexvols for Oracle NFS volumes
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Flexvols for Oracle Database
      include_tasks: nfs_volume_create.yml
      tags:
        - ontap_flexvol_create
  when: ontap_nodes_validity|bool and ontap_aggregates_validity|bool and ontap_vlan_validity|bool
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Flexvols for Oracle Datastore] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ONTAP task for creating NFS LIFs
# Create two lifs for Oracle NFS volume client access
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Lifs for Oracle NFS datastores client access
      include_tasks: nfs_lif_create.yml
      tags:
        - ontap_nfs_lif
  when: ontap_nodes_validity|bool and ontap_aggregates_validity|bool and ontap_vlan_validity|bool
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Lifs for Oracle NFS datastores client access] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.            
